const $=s=>document.querySelector(s);let cache={models:[],members:[],settings:{}};
const api=async(path,opt={})=>{const token=localStorage.getItem('yoyo-token');const r=await fetch('/api'+path,{...opt,headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{}),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'请求失败');return d};
function message(text,error=false){const t=$('#toast');t.textContent=text;t.className=error?'show error':'show';clearTimeout(message.timer);message.timer=setTimeout(()=>t.className='',2600)}
function safe(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderModels(){const box=$('#models');$('#pricingModel').innerHTML=cache.models.map(m=>`<option value="${m.id}">${safe(m.name)} · ${safe(m.category)}</option>`).join('')||'<option>请先创建模型</option>';box.innerHTML=cache.models.length?cache.models.map(m=>`<article class="model"><div><b>${safe(m.name)} · ${safe(m.provider||'custom')}</b><small>${safe(m.model_identifier||'—')} · ${safe(m.protocol||'openai-compatible')} · ${m.is_enabled?'启用':'停用'}</small><em>${safe(m.api_url||'')}</em></div><div><button class="toggle" data-test="${m.id}">在线测试</button><button class="toggle ${m.is_enabled?'enabled':''}" data-model="${m.id}" data-enabled="${m.is_enabled}">${m.is_enabled?'停用':'启用'}</button></div></article>`).join(''):'<div class="empty">还没有模型。请先保存模型连接配置。</div>'}
function renderMembers(){const box=$('#members');box.innerHTML=cache.members.length?cache.members.map(u=>`<article class="member"><div><b>${safe(u.nickname||'未命名用户')}</b><small>${safe(u.phone)} · 当前积分：${safe(u.points)} · ${u.role==='admin'?'管理员':u.is_banned?'已停用':'正常用户'}</small></div><div><form class="adjust" data-user="${u.id}"><input name="amount" required type="number" step="1" placeholder="+赠送 / -扣减"><input name="remark" maxlength="100" placeholder="调整备注"><button>确认调整</button></form>${u.role==='admin'?'':`<button class="ban" data-ban="${u.id}" data-banned="${u.is_banned}">${u.is_banned?'恢复用户':'停用用户'}</button>`}</div></article>`).join(''):'<div class="empty">未找到匹配用户。</div>'}
function renderLedger(rows){$('#ledger').innerHTML=rows.length?rows.map(x=>`<article class="member"><div><b>${safe(x.phone)} · ${safe(x.amount)} 积分</b><small>${safe(x.change_type)} · ${safe(x.remark||'—')}</small></div><strong>${safe(x.balance_after)}</strong></article>`).join(''):'<div class="empty">暂时没有积分流水。</div>'}
function renderRules(){const p=cache.settings.points||{};$('#registerBonus').value=p.register_bonus??128;$('#dailyCheckin').value=p.daily_checkin??3;$('#seventhDayBonus').value=p.seventh_day_bonus??10}
async function load(){try{const [me,summary,models,members,settings]=await Promise.all([api('/me'),api('/admin/dashboard'),api('/admin/models'),api('/admin/users'),api('/admin/settings')]);if(me?.role!=='admin')throw Error('当前账号不是超级管理员');cache={models,members,settings};$('#login').hidden=true;$('#dashboard').hidden=false;$('#operator').textContent=`管理员：${me.phone}`;$('#users').textContent=summary.users;$('#stories').textContent=summary.stories;$('#tasks').textContent=summary.tasksToday;$('#points').textContent=summary.pointsConsumed;renderModels();renderMembers();renderRules()}catch(e){$('#error').textContent=e.message;if(localStorage.getItem('yoyo-token'))message(e.message,true)}}
$('#loginBtn').onclick=async()=>{try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({phone:$('#phone').value,password:$('#password').value})});localStorage.setItem('yoyo-token',d.token);await load()}catch(e){$('#error').textContent=e.message}};
$('#refresh').onclick=async()=>{await load();message('后台数据已刷新')};$('#logout').onclick=()=>{localStorage.removeItem('yoyo-token');location.reload()};
document.querySelector('.tabs').onclick=async e=>{const b=e.target.closest('[data-tab]');if(!b)return;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['models','members','rules','ledger'].forEach(x=>$(`#${x}Tab`).hidden=x!==b.dataset.tab);if(b.dataset.tab==='ledger')try{renderLedger(await api('/admin/ledger'))}catch(err){message(err.message,true)}};
$('#modelForm').onsubmit=async e=>{e.preventDefault();try{let requestConfig={};if($('#requestConfig').value.trim())requestConfig=JSON.parse($('#requestConfig').value);await api('/admin/models',{method:'POST',body:JSON.stringify({name:$('#modelName').value.trim(),category:$('#modelCategory').value,provider:$('#modelProvider').value.trim(),modelIdentifier:$('#modelIdentifier').value.trim(),protocol:$('#modelProtocol').value,apiUrl:$('#modelUrl').value.trim(),apiKeyRef:$('#apiKeyRef').value.trim(),timeoutMs:Number($('#timeoutMs').value),maxRetries:Number($('#maxRetries').value),requestConfig})});e.target.reset();$('#timeoutMs').value=30000;$('#maxRetries').value=2;await load();message('模型配置已保存')}catch(err){message(err.message,true)}};
$('#pricingForm').onsubmit=async e=>{e.preventDefault();try{const pricing={inputPerMillion:Number($('#priceInput').value||0),outputPerMillion:Number($('#priceOutput').value||0),perMinute:Number($('#priceMinute').value||0),perImage:{'512x512':Number($('#price512').value||0),'1024x1024':Number($('#price1024').value||0)}};await api(`/admin/models/${$('#pricingModel').value}`,{method:'PATCH',body:JSON.stringify({pricing})});message('计费策略已保存')}catch(err){message(err.message,true)}};$('#models').onclick=async e=>{const b=e.target.closest('[data-model],[data-test]');if(!b)return;try{if(b.dataset.test){b.disabled=true;b.textContent='测试中…';const d=await api(`/admin/models/${b.dataset.test}/test`,{method:'POST'});message(`测试成功：${d.status}，${d.elapsedMs}ms`)}else{await api(`/admin/models/${b.dataset.model}`,{method:'PATCH',body:JSON.stringify({isEnabled:b.dataset.enabled!=='true'})});await load();message('模型状态已更新')}}catch(err){message(err.message,true)}finally{b.disabled=false;if(b.dataset.test)b.textContent='在线测试'}};
let searchTimer;$('#userSearch').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(async()=>{try{cache.members=await api('/admin/users?query='+encodeURIComponent(e.target.value));renderMembers()}catch(err){message(err.message,true)}},250)};
$('#members').onsubmit=async e=>{const f=e.target.closest('.adjust');if(!f)return;e.preventDefault();const form=new FormData(f);try{const u=await api(`/admin/users/${f.dataset.user}/points`,{method:'POST',body:JSON.stringify({amount:Number(form.get('amount')),remark:form.get('remark')})});cache.members=cache.members.map(x=>x.id===u.id?{...x,points:u.points}:x);renderMembers();message('积分已调整并已记录审计日志')}catch(err){message(err.message,true)}};$('#members').onclick=async e=>{const b=e.target.closest('[data-ban]');if(!b)return;try{const u=await api(`/admin/users/${b.dataset.ban}`,{method:'PATCH',body:JSON.stringify({isBanned:b.dataset.banned!=='true'})});cache.members=cache.members.map(x=>x.id===u.id?{...x,is_banned:u.is_banned}:x);renderMembers();message('用户状态已更新')}catch(err){message(err.message,true)}};
$('#rulesForm').onsubmit=async e=>{e.preventDefault();try{const value={...(cache.settings.points||{}),register_bonus:Number($('#registerBonus').value),daily_checkin:Number($('#dailyCheckin').value),seventh_day_bonus:Number($('#seventhDayBonus').value)};await api('/admin/settings/points',{method:'PUT',body:JSON.stringify({value})});cache.settings.points=value;message('运营积分规则已保存并生效')}catch(err){message(err.message,true)}};
if(localStorage.getItem('yoyo-token'))load();
