const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const state={points:Number(localStorage.getItem('story-points')||128),voices:JSON.parse(localStorage.getItem('story-voices')||'[]'),stories:JSON.parse(localStorage.getItem('story-stories')||'[]')};
$('#points').textContent=state.points;
function route(){const r=location.hash.replace('#','')||'home';$$('.page').forEach(p=>p.classList.toggle('active',p.id===`${r}-page`));$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));$$('.mobile-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+r));window.scrollTo(0,0)}addEventListener('hashchange',route);route();
$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{if(e.target.files[0]) addVoice(e.target.files[0].name,Math.round(e.target.files[0].size/1000)+' KB 音频')};
function addVoice(name,meta='刚刚录制'){state.voices.push({name:name.replace(/\.[^.]+$/,''),meta});localStorage.setItem('story-voices',JSON.stringify(state.voices));renderVoices()}
function renderVoices(){const list=$('#voiceList');$('#voiceCount').textContent=`${state.voices.length} / 5`;list.innerHTML=state.voices.length?state.voices.map((v,i)=>`<div class="voice-item"><div class="voice-dot">🎙️</div><div><b>${v.name}</b><small>${v.meta}</small></div><button data-delete="${i}">删除</button></div>`).join(''):`<div class="empty-state">还没有声音样本<br><span>录下第一段声音，让故事拥有你的温度。</span></div>`;$$('[data-delete]').forEach(b=>b.onclick=()=>{state.voices.splice(+b.dataset.delete,1);localStorage.setItem('story-voices',JSON.stringify(state.voices));renderVoices()})}renderVoices();
let recorder,chunks=[],started;$('#recordBtn').onclick=async()=>{if(state.voices.length>=5)return alert('最多保存 5 组声音样本');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());addVoice('我的声音样本',`${Math.round((Date.now()-started)/1000)} 秒 · 质量良好`);$('#recordStatus').textContent='样本已保存，可以去创作故事了 ✨'};recorder.start();started=Date.now();$('#recordBtn').disabled=true;$('#stopBtn').disabled=false;$('#recordStatus').textContent='正在录音… 请朗读上面的引导语';$$('.waveform i').forEach((x,i)=>x.style.height=(10+Math.random()*30)+'px')}catch(e){alert('无法访问麦克风，请检查浏览器权限，或选择上传音频。')}};$('#stopBtn').onclick=()=>{if(recorder&&recorder.state==='recording'){recorder.stop();$('#recordBtn').disabled=false;$('#stopBtn').disabled=true}};
$$('[data-topic]').forEach(b=>b.onclick=()=>$('#topic').value=b.dataset.topic);$('#topic').oninput=()=>$('#saveStatus').textContent='● 正在保存…';setInterval(()=>$('#saveStatus').textContent='● 自动保存已开启',1500);
$('#generateBtn').onclick=()=>{const topic=$('#topic').value.trim()||'小兔子第一次去月亮上旅行';const style=$('#style').value;const age=$('#age').value;const title=topic.length>14?topic.slice(0,14)+'…':topic;$('#previewCover').innerHTML=`<span>🌙</span><small>${title}</small>`;$('#previewContent').innerHTML=`<div class="eyebrow">AI STORY · ${age}</div><h2>${title}</h2><p>在一个${style}的夜晚，${topic}。月光像一条银色的小路，悄悄铺到了窗边。小主人公深吸一口气，带着勇气和好奇心，踏上了这段奇妙的旅程。</p><p>一路上，它遇见了温柔的朋友，也发现每一次小小的尝试，都会带来闪闪发光的成长。</p><button class="btn primary" id="saveStory">♡ 保存到作品库</button>`;$('#saveStory').onclick=()=>{state.stories.push({title,age,style});localStorage.setItem('story-stories',JSON.stringify(state.stories));$('#storyCount').textContent=3+state.stories.length;alert('故事已保存到作品库 ✨')};$('#generateBtn').textContent='✨ 重新生成故事';};
function play(title){$('#playerTitle').textContent=title;$('#playerState').textContent='正在播放 · 温柔妈妈';$('#player').classList.add('show');$('#playerPlay').textContent='❚❚';let p=0;clearInterval(window.playTimer);window.playTimer=setInterval(()=>{$('#playerProgress').style.width=(p%101)+'%';p+=1},200)}$$('.play-story').forEach(b=>b.onclick=()=>play(b.dataset.title));$('#playerPlay').onclick=()=>{$('#playerState').textContent=$('#playerState').textContent.includes('正在')?'已暂停':'正在播放 · 温柔妈妈';$('#playerPlay').textContent=$('#playerPlay').textContent==='❚❚'?'▶':'❚❚'};$('#playerClose').onclick=()=>$('#player').classList.remove('show');$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#features').scrollIntoView());
