const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const state={points:Number(localStorage.getItem('story-points')||128),voices:JSON.parse(localStorage.getItem('story-voices')||'[]'),stories:JSON.parse(localStorage.getItem('story-stories')||'[]')};const API='/api';const token=()=>localStorage.getItem('yoyo-token');async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(API+path,{...opt,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'请求失败');return d}
$('#points').textContent=state.points;
function openAuth(){if($('#authModal'))return;document.body.insertAdjacentHTML('beforeend',`<div class="auth-modal" id="authModal"><div class="auth-box"><button class="auth-close" onclick="document.querySelector('#authModal').remove()">×</button><div class="eyebrow">WELCOME TO STORY PLANET</div><h2 id="authTitle">登录故事星球</h2><input id="authPhone" placeholder="手机号" maxlength="11"><input id="authPassword" type="password" placeholder="密码（至少8位）"><input id="authNickname" placeholder="昵称（注册时填写）" hidden><button class="btn primary" id="authSubmit">登录</button><p id="authError"></p><button class="auth-switch" id="authSwitch">还没有账号？立即注册</button></div></div>`);let reg=false;$('#authSwitch').onclick=()=>{reg=!reg;$('#authTitle').textContent=reg?'注册故事星球':'登录故事星球';$('#authSubmit').textContent=reg?'注册':'登录';$('#authNickname').hidden=!reg;$('#authSwitch').textContent=reg?'已有账号？去登录':'还没有账号？立即注册'};$('#authSubmit').onclick=async()=>{try{const d=await api(reg?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify({phone:$('#authPhone').value,password:$('#authPassword').value,nickname:$('#authNickname').value})});localStorage.setItem('yoyo-token',d.token);location.reload()}catch(e){$('#authError').textContent=e.message}}}
$('#pointsBtn').onclick=openAuth;$('.avatar').onclick=openAuth;
function route(){const r=location.hash.replace('#','')||'home';$$('.page').forEach(p=>p.classList.toggle('active',p.id===`${r}-page`));$$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===r));$$('.mobile-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+r));window.scrollTo(0,0)}addEventListener('hashchange',route);route();
$('#uploadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{if(e.target.files[0]) addVoice(e.target.files[0].name,Math.round(e.target.files[0].size/1000)+' KB 音频')};
async function addVoice(name,meta='刚刚录制'){if(token()&&$('#fileInput').files[0]){const body=new FormData();body.append('audio',$('#fileInput').files[0]);body.append('name',name.replace(/\.[^.]+$/,''));const r=await fetch(API+'/voices/upload',{method:'POST',headers:{Authorization:`Bearer ${token()}`},body});if(!r.ok)return alert((await r.json()).error);state.voices.unshift(await r.json());renderVoices();return}state.voices.push({name:name.replace(/\.[^.]+$/,''),meta});localStorage.setItem('story-voices',JSON.stringify(state.voices));renderVoices()}
function renderVoices(){const list=$('#voiceList');$('#voiceCount').textContent=`${state.voices.length} / 5`;list.innerHTML=state.voices.length?state.voices.map((v,i)=>`<div class="voice-item"><div class="voice-dot">🎙️</div><div><b>${v.name}</b><small>${v.meta}</small></div><button data-delete="${i}">删除</button></div>`).join(''):`<div class="empty-state">还没有声音样本<br><span>录下第一段声音，让故事拥有你的温度。</span></div>`;$$('[data-delete]').forEach(b=>b.onclick=()=>{state.voices.splice(+b.dataset.delete,1);localStorage.setItem('story-voices',JSON.stringify(state.voices));renderVoices()})}renderVoices();
let recorder,chunks=[],started;$('#recordBtn').onclick=async()=>{if(state.voices.length>=5)return alert('最多保存 5 组声音样本');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());addVoice('我的声音样本',`${Math.round((Date.now()-started)/1000)} 秒 · 质量良好`);$('#recordStatus').textContent='样本已保存，可以去创作故事了 ✨'};recorder.start();started=Date.now();$('#recordBtn').disabled=true;$('#stopBtn').disabled=false;$('#recordStatus').textContent='正在录音… 请朗读上面的引导语';$$('.waveform i').forEach((x,i)=>x.style.height=(10+Math.random()*30)+'px')}catch(e){alert('无法访问麦克风，请检查浏览器权限，或选择上传音频。')}};$('#stopBtn').onclick=()=>{if(recorder&&recorder.state==='recording'){recorder.stop();$('#recordBtn').disabled=false;$('#stopBtn').disabled=true}};
$$('[data-topic]').forEach(b=>b.onclick=()=>$('#topic').value=b.dataset.topic);$('#topic').oninput=()=>$('#saveStatus').textContent='● 正在保存…';setInterval(()=>$('#saveStatus').textContent='● 自动保存已开启',1500);
$('#generateBtn').onclick=()=>{const topic=$('#topic').value.trim()||'小兔子第一次去月亮上旅行';const style=$('#style').value;const age=$('#age').value;const title=topic.length>14?topic.slice(0,14)+'…':topic;$('#previewCover').innerHTML=`<span>🌙</span><small>${title}</small>`;$('#previewContent').innerHTML=`<div class="eyebrow">AI STORY · ${age}</div><h2>${title}</h2><p>在一个${style}的夜晚，${topic}。月光像一条银色的小路，悄悄铺到了窗边。小主人公深吸一口气，带着勇气和好奇心，踏上了这段奇妙的旅程。</p><p>一路上，它遇见了温柔的朋友，也发现每一次小小的尝试，都会带来闪闪发光的成长。</p><button class="btn primary" id="saveStory">♡ 保存到作品库</button>`;$('#saveStory').onclick=()=>{state.stories.push({title,age,style});localStorage.setItem('story-stories',JSON.stringify(state.stories));$('#storyCount').textContent=3+state.stories.length;alert('故事已保存到作品库 ✨')};$('#generateBtn').textContent='✨ 重新生成故事';};
function play(title){$('#playerTitle').textContent=title;$('#playerState').textContent='正在播放 · 温柔妈妈';$('#player').classList.add('show');$('#playerPlay').textContent='❚❚';let p=0;clearInterval(window.playTimer);window.playTimer=setInterval(()=>{$('#playerProgress').style.width=(p%101)+'%';p+=1},200)}$$('.play-story').forEach(b=>b.onclick=()=>play(b.dataset.title));$('#playerPlay').onclick=()=>{$('#playerState').textContent=$('#playerState').textContent.includes('正在')?'已暂停':'正在播放 · 温柔妈妈';$('#playerPlay').textContent=$('#playerPlay').textContent==='❚❚'?'▶':'❚❚'};$('#playerClose').onclick=()=>$('#player').classList.remove('show');$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#features').scrollIntoView());
