create extension if not exists pgcrypto;
create table if not exists users (id uuid primary key default gen_random_uuid(), phone varchar(32) unique not null, password_hash text not null, nickname varchar(80) not null, points numeric(12,2) not null default 128, is_banned boolean not null default false, created_at timestamptz not null default now());
create table if not exists children_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, name varchar(80) not null, age smallint not null check(age between 1 and 12), created_at timestamptz not null default now());
create table if not exists voice_samples (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, name varchar(120) not null, file_url text, duration numeric(8,2), quality_score numeric(5,2), is_default boolean not null default false, status varchar(20) not null default 'ready', created_at timestamptz not null default now());
create table if not exists system_voices (id uuid primary key default gen_random_uuid(), name varchar(80) not null unique, description text not null, category varchar(40) not null, demo_url text, is_active boolean not null default true, sort_order int not null default 0);
create table if not exists stories (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, child_profile_id uuid references children_profiles(id) on delete set null, title varchar(200) not null, content text not null, age_range varchar(30) not null, style varchar(40) not null, tags text[] not null default '{}', status varchar(20) not null default 'draft', is_public boolean not null default false, view_count int not null default 0, like_count int not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists story_audio (id uuid primary key default gen_random_uuid(), story_id uuid not null references stories(id) on delete cascade, voice_sample_id uuid references voice_samples(id) on delete set null, system_voice_id uuid references system_voices(id) on delete set null, audio_url text, format varchar(10) not null default 'mp3', status varchar(20) not null default 'pending', duration numeric(8,2), created_at timestamptz not null default now());
create table if not exists points_log (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, change_type varchar(40) not null, amount numeric(12,2) not null, balance_after numeric(12,2) not null, tokens_consumed bigint, story_id uuid references stories(id) on delete set null, remark text, created_at timestamptz not null default now());
create table if not exists checkin_records (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, checkin_date date not null, consecutive_days int not null default 1, points_earned numeric(12,2) not null default 3, unique(user_id, checkin_date));
alter table users owner to yoyostory;
alter table children_profiles owner to yoyostory;
alter table voice_samples owner to yoyostory;
alter table system_voices owner to yoyostory;
alter table stories owner to yoyostory;
alter table story_audio owner to yoyostory;
alter table points_log owner to yoyostory;
alter table checkin_records owner to yoyostory;
alter table users add column if not exists role varchar(20) not null default 'user';
alter table users add column if not exists last_login_at timestamptz;
create table if not exists ai_models (id uuid primary key default gen_random_uuid(), name varchar(100) not null, category varchar(30) not null, api_url text, price_per_million numeric(12,2) not null default 0, is_enabled boolean not null default true, created_at timestamptz not null default now());
create table if not exists ai_tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id) on delete cascade, task_type varchar(30) not null, status varchar(20) not null default 'queued', provider varchar(100), input_json jsonb not null default '{}', output_json jsonb, error_message text, attempts int not null default 0, created_at timestamptz not null default now(), started_at timestamptz, finished_at timestamptz);
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete set null, action varchar(80) not null, resource_type varchar(40), resource_id uuid, ip_address inet, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists platform_settings (key varchar(80) primary key, value_json jsonb not null default '{}', updated_at timestamptz not null default now());
alter table ai_models owner to yoyostory;
alter table ai_tasks owner to yoyostory;
alter table audit_logs owner to yoyostory;
alter table platform_settings owner to yoyostory;
insert into platform_settings(key,value_json) values ('points', '{"register_bonus":128,"daily_checkin":3,"max_voice_samples":5}'),('content_safety','{"enabled":true}') on conflict(key) do nothing;
insert into system_voices(name,description,category,sort_order) values ('温柔妈妈','温暖轻柔，适合睡前故事','睡前',1),('活泼姐姐','明亮活泼，节奏感强','冒险',2),('知性阿姨','清晰知性，娓娓道来','科普',3),('暖心爸爸','低沉温暖，亲和力强','陪伴',4),('阳光哥哥','朝气蓬勃，感染力强','励志',5),('智慧爷爷','沉稳睿智，语重心长','知识',6),('小星星（女童）','奶声奶气，适合低龄','低龄',7),('小月亮（女童）','清亮灵动，活泼可爱','儿童',8),('小太阳（男童）','元气憨态可掬','儿童',9),('小勇士（男童）','沉稳勇敢，冒险故事','冒险',10),('绘本旁白','标准普通话，全场景','旁白',11) on conflict(name) do nothing;
create index if not exists stories_user_created_idx on stories(user_id, created_at desc);
create index if not exists points_log_user_created_idx on points_log(user_id, created_at desc);
