import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
import { calculatePoints } from './billing.js';
import { generateVerificationCode, sendAliyunVerificationCode } from './aliyun-sms.js';
const { Pool } = pg;
const execFileAsync = promisify(execFile);
const app = express();
const port = Number(process.env.PORT || 4101);
const isProduction = process.env.NODE_ENV === 'production';
if (isProduction && (!process.env.DATABASE_URL || !process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32)) {
  throw new Error('生产环境必须配置 DATABASE_URL 和至少 32 位 JWT_SECRET');
}
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 10, idleTimeoutMillis: 30000 });
const uploadDir = process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads'); fs.mkdirSync(uploadDir, { recursive: true });
const allowedOrigin = process.env.WEB_ORIGIN || (isProduction ? undefined : '*');
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: allowedOrigin, credentials: Boolean(allowedOrigin && allowedOrigin !== '*') })); app.use(express.json({ limit: '1mb', verify:(req,_res,buf)=>{if(req.originalUrl==='/api/payments/webhook')req.rawBody=Buffer.from(buf)} }));
app.use('/api/', rateLimit({ windowMs: 60 * 1000, limit: 100, standardHeaders: true, legacyHeaders: false }));
const upload = multer({ dest: uploadDir, limits: { fileSize: 50 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, /^(audio|video)\//.test(file.mimetype)) });
const documentUpload = multer({ dest: uploadDir, limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, file.mimetype==='text/plain'||file.mimetype==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'||/\.(txt|docx)$/i.test(file.originalname)) });
const sign = user => jwt.sign({ sub: user.id, phone: user.phone }, process.env.JWT_SECRET, { expiresIn: '15m' });
function auth(req,res,next){try{const token=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(token,process.env.JWT_SECRET);next()}catch{res.status(401).json({error:'登录已过期，请重新登录'})}}
async function admin(req,res,next){const {rows}=await pool.query('select role from users where id=$1',[req.user.sub]);if(rows[0]?.role!=='admin')return res.status(403).json({error:'需要管理员权限'});next()}
async function audit(req,action,type,id,metadata={}){await pool.query('insert into audit_logs(user_id,action,resource_type,resource_id,ip_address,metadata) values($1,$2,$3,$4,$5,$6)',[req.user?.sub,action,type,id,req.ip,metadata])}
async function tx(fn){const c=await pool.connect();try{await c.query('begin');const out=await fn(c);await c.query('commit');return out}catch(e){await c.query('rollback');throw e}finally{c.release()}}
async function activeModel(category,name){const {rows}=await pool.query('select id,name,category,price_per_million from ai_models where category=$1 and is_enabled=true and ($2::text is null or name=$2) order by created_at desc limit 1',[category,name||null]);return rows[0]||null}
async function chargeUsage({userId,model,taskId,storyId,category,inputTokens=0,outputTokens=0}){const totalTokens=Math.max(0,Number(inputTokens||0)+Number(outputTokens||0));const points=calculatePoints(totalTokens,model?.price_per_million);return tx(async c=>{const user=(await c.query('select points from users where id=$1 for update',[userId])).rows[0];if(!user)throw Error('用户不存在');if(Number(user.points)<points){const e=Error('积分不足，请充值后重试');e.code='INSUFFICIENT_POINTS';throw e}const balance=Number((Number(user.points)-points).toFixed(4));await c.query('update users set points=$1 where id=$2',[balance,userId]);await c.query('insert into model_usage(user_id,model_id,task_id,story_id,category,model_name,input_tokens,output_tokens,total_tokens,points_charged) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[userId,model?.id||null,taskId||null,storyId||null,category,model?.name||'platform-fallback',inputTokens,outputTokens,totalTokens,points]);await c.query('insert into points_log(user_id,change_type,amount,balance_after,tokens_consumed,story_id,remark) values($1,$2,$3,$4,$5,$6,$7)',[userId,`${category}_model`,-points,balance,totalTokens,storyId||null,`${model?.name||'平台默认模型'} ${totalTokens} Tokens`]);return {totalTokens,points,balance}})}
async function completePayment(orderNo,tradeNo){return tx(async c=>{const order=(await c.query('select * from billing_orders where order_no=$1 for update',[orderNo])).rows[0];if(!order)throw Error('订单不存在');if(order.status==='paid')return {order,alreadyPaid:true};if(order.status!=='pending')throw Error('订单状态不可支付');const user=(await c.query('select points from users where id=$1 for update',[order.user_id])).rows[0];const balance=Number(user.points)+Number(order.points);const paid=(await c.query("update billing_orders set status='paid',provider_trade_no=$1,paid_at=now(),updated_at=now() where id=$2 returning *",[tradeNo||null,order.id])).rows[0];await c.query('update users set points=$1 where id=$2',[balance,order.user_id]);await c.query('insert into points_log(user_id,change_type,amount,balance_after,remark) values($1,$2,$3,$4,$5)',[order.user_id,'self_recharge',order.points,balance,`订单 ${order.order_no}`]);return {order:paid,balance,alreadyPaid:false}})}
async function verifyCaptcha(token,ip){if(!process.env.CAPTCHA_VERIFY_URL)return !isProduction;const r=await fetch(process.env.CAPTCHA_VERIFY_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:process.env.CAPTCHA_SECRET,token,remoteip:ip})});if(!r.ok)return false;const result=await r.json();return result.success===true}
async function verifySmsCode(phone,code,purpose){const {rows}=await pool.query('select * from sms_codes where phone=$1 and purpose=$2 and used_at is null and expires_at>now() order by created_at desc limit 1',[phone,purpose]);const record=rows[0];if(!record||record.attempts>=5||!(await bcrypt.compare(String(code||''),record.code_hash)))return false;await pool.query('update sms_codes set used_at=now(),attempts=attempts+1 where id=$1',[record.id]);return true}
function decodeXml(text){return text.replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
async function extractStoryDocument(file){if(/\.txt$/i.test(file.originalname)||file.mimetype==='text/plain')return fs.readFileSync(file.path,'utf8').replace(/^\uFEFF/,'').trim();const {stdout}=await execFileAsync('unzip',['-p',file.path,'word/document.xml'],{maxBuffer:10*1024*1024});const text=[...stdout.matchAll(/<w:p[ >][\s\S]*?<\/w:p>/g)].map(m=>decodeXml(m[0]).trim()).filter(Boolean).join('\n\n');if(!text)throw Error('文档中没有可导入的正文');return text}
app.get('/api/health', async (_,res)=>{try{await pool.query('select 1');res.json({ok:true,service:'yoyostory-api',release:process.env.RELEASE_SHA||'local'})}catch{res.status(503).json({ok:false})}});
app.post('/api/auth/sms/request',async(req,res)=>{const phone=req.body?.phone;if(!/^1\d{10}$/.test(phone||''))return res.status(400).json({error:'手机号格式不正确'});try{const recent=await pool.query("select 1 from sms_codes where phone=$1 and purpose='register' and created_at>now()-interval '60 seconds'",[phone]);if(recent.rows[0])return res.status(429).json({error:'请一分钟后再试'});const code=generateVerificationCode();if(process.env.ALIYUN_ACCESS_KEY_ID){await sendAliyunVerificationCode(phone,code)}else if(process.env.SMS_SEND_URL){const r=await fetch(process.env.SMS_SEND_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.SMS_API_KEY?{Authorization:`Bearer ${process.env.SMS_API_KEY}`}:{})},body:JSON.stringify({phone,code,purpose:'register'})});if(!r.ok)throw Error('短信服务不可用')}else if(isProduction)throw Error('短信服务未配置');await pool.query("insert into sms_codes(phone,purpose,code_hash,expires_at) values($1,'register',$2,now()+interval '5 minutes')",[phone,await bcrypt.hash(code,10)]);res.json({ok:true,expiresIn:300,...(!isProduction&&!process.env.ALIYUN_ACCESS_KEY_ID?{debugCode:code}:{})})}catch(e){res.status(503).json({error:e.message||'短信发送失败'})}});
app.post('/api/auth/register', async (req,res)=>{const {phone,password,nickname='故事星球用户',smsCode,captchaToken}=req.body||{};if(!/^1\d{10}$/.test(phone||'')||!password||password.length<8)return res.status(400).json({error:'手机号或密码格式不正确'});try{if(process.env.CAPTCHA_VERIFY_URL&&!(await verifyCaptcha(captchaToken,req.ip)))return res.status(400).json({error:'人机验证失败'});if(isProduction&&!(await verifySmsCode(phone,smsCode,'register')))return res.status(400).json({error:'短信验证码无效或已过期'});const setting=await pool.query("select value_json from platform_settings where key='points'");const bonus=Math.max(0,Number(setting.rows[0]?.value_json?.register_bonus||0));const hash=await bcrypt.hash(password,12);const {rows}=await pool.query('insert into users(phone,password_hash,nickname,points) values($1,$2,$3,$4) returning id,phone, nickname,points',[phone,hash,nickname,bonus]);res.status(201).json({token:sign(rows[0]),user:rows[0]})}catch(e){res.status(e.code==='23505'?409:503).json({error:e.code==='23505'?'手机号已注册':'注册失败'})}});
app.post('/api/auth/login', async (req,res)=>{const {phone,password}=req.body||{};const {rows}=await pool.query('select id,phone,nickname,points,password_hash,is_banned from users where phone=$1',[phone]);const u=rows[0];if(!u||u.is_banned||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'手机号或密码错误'});await pool.query('update users set last_login_at=now() where id=$1',[u.id]);delete u.password_hash;res.json({token:sign(u),user:u})});
app.get('/api/me',auth,async(req,res)=>{const {rows}=await pool.query('select id,phone,nickname,points,role,created_at from users where id=$1',[req.user.sub]);res.json(rows[0]||null)});
app.get('/api/billing',auth,async(req,res)=>{const {rows}=await pool.query('select id,change_type,amount,balance_after,tokens_consumed,remark,created_at from points_log where user_id=$1 order by created_at desc limit 100',[req.user.sub]);res.json(rows)});
app.get('/api/billing/summary',auth,async(req,res)=>{const [balance,usage,orders]=await Promise.all([pool.query('select points from users where id=$1',[req.user.sub]),pool.query('select coalesce(sum(points_charged),0)::numeric as consumed,coalesce(sum(total_tokens),0)::bigint as tokens from model_usage where user_id=$1',[req.user.sub]),pool.query("select coalesce(sum(points),0)::numeric as purchased from billing_orders where user_id=$1 and status='paid'",[req.user.sub])]);res.json({balance:balance.rows[0]?.points||0,consumed:usage.rows[0]?.consumed||0,tokens:usage.rows[0]?.tokens||0,purchased:orders.rows[0]?.purchased||0})});
app.get('/api/billing/orders',auth,async(req,res)=>{const {rows}=await pool.query('select id,order_no,points,amount,currency,status,provider,paid_at,created_at from billing_orders where user_id=$1 order by created_at desc limit 100',[req.user.sub]);res.json(rows)});
app.post('/api/billing/orders',auth,async(req,res)=>{const points=Number(req.body?.points);if(!Number.isFinite(points)||points<10||points>100000)return res.status(400).json({error:'充值积分范围为 10 至 100000'});const orderNo=`YS${Date.now()}${Math.floor(Math.random()*10000).toString().padStart(4,'0')}`;const amount=Number((points/10).toFixed(2));const {rows}=await pool.query('insert into billing_orders(user_id,order_no,points,amount,provider) values($1,$2,$3,$4,$5) returning *',[req.user.sub,orderNo,points,amount,process.env.PAYMENT_PROVIDER||'manual']);res.status(201).json({order:rows[0],message:'订单已创建，等待支付回调'});});
app.post('/api/payments/webhook',async(req,res)=>{try{if(!process.env.PAYMENT_WEBHOOK_SECRET)return res.status(503).json({error:'支付回调未配置'});const signature=req.headers['x-payment-signature'];const raw=req.rawBody;if(!raw)return res.status(400).json({error:'缺少支付载荷'});const expected=crypto.createHmac('sha256',process.env.PAYMENT_WEBHOOK_SECRET).update(raw).digest('hex');if(typeof signature!=='string'||signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected)))return res.status(401).json({error:'无效支付签名'});const event=req.body;if(event.status!=='paid'||!event.orderNo)return res.status(400).json({error:'无效支付事件'});const result=await completePayment(event.orderNo,event.tradeNo);res.json({ok:true,alreadyPaid:result.alreadyPaid})}catch(e){console.error(e);res.status(400).json({error:e.message||'支付回调处理失败'})}});
app.get('/api/tasks/:id',auth,async(req,res)=>{const {rows}=await pool.query('select id,task_type,status,output_json,error_message,created_at,started_at,finished_at from ai_tasks where id=$1 and user_id=$2',[req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'任务不存在'});res.json(rows[0])});
app.get('/api/settings/public',async(_,res)=>{const {rows}=await pool.query("select key,value_json from platform_settings where key in ('points','content_safety')");res.json(Object.fromEntries(rows.map(r=>[r.key,r.value_json])))});
app.get('/api/voices/system',async(_,res)=>{const {rows}=await pool.query('select id,name,description,category,demo_url from system_voices where is_active=true order by sort_order');res.json(rows)});
app.get('/api/voices',auth,async(req,res)=>{const {rows}=await pool.query('select id,name,file_url,duration,quality_score,is_default,status,created_at from voice_samples where user_id=$1 order by created_at desc',[req.user.sub]);res.json(rows)});
app.post('/api/voices/upload',auth,upload.single('audio'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'请上传音频文件'});const count=await pool.query('select count(*) from voice_samples where user_id=$1',[req.user.sub]);if(Number(count.rows[0].count)>=5){fs.unlinkSync(req.file.path);return res.status(409).json({error:'最多保存5组声音样本'})}const {rows}=await pool.query('insert into voice_samples(user_id,name,file_url,quality_score) values($1,$2,$3,$4) returning *',[req.user.sub,req.body.name||'我的声音样本',`/uploads/${req.file.filename}`,92]);res.status(201).json(rows[0])});
app.patch('/api/voices/:id',auth,async(req,res)=>{const {name,isDefault}=req.body||{};if(typeof isDefault==='boolean'&&isDefault){await tx(async c=>{await c.query('update voice_samples set is_default=false where user_id=$1',[req.user.sub]);const out=await c.query('update voice_samples set is_default=true where id=$1 and user_id=$2 returning id,name,file_url,duration,quality_score,is_default,status,created_at',[req.params.id,req.user.sub]);if(!out.rows[0]){const e=Error('声音样本不存在');e.code='NOT_FOUND';throw e}});return res.json({ok:true})}const {rows}=await pool.query('update voice_samples set name=coalesce($1,name) where id=$2 and user_id=$3 returning id,name,file_url,duration,quality_score,is_default,status,created_at',[String(name||'').slice(0,120)||null,req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'声音样本不存在'});res.json(rows[0])});
app.delete('/api/voices/:id',auth,async(req,res)=>{const {rows}=await pool.query('delete from voice_samples where id=$1 and user_id=$2 returning file_url',[req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'声音样本不存在'});if(rows[0].file_url?.startsWith('/uploads/'))fs.unlink(path.join(uploadDir,path.basename(rows[0].file_url)),()=>{});res.status(204).end()});
app.get('/api/stories',auth,async(req,res)=>{const {rows}=await pool.query('select id,title,content,age_range,style,tags,status,is_public,view_count,like_count,created_at,updated_at from stories where user_id=$1 order by updated_at desc',[req.user.sub]);res.json(rows)});
app.get('/api/stories/:id/audio',auth,async(req,res)=>{const own=await pool.query('select id from stories where id=$1 and user_id=$2',[req.params.id,req.user.sub]);if(!own.rows[0])return res.status(404).json({error:'作品不存在'});const {rows}=await pool.query('select id,audio_url,format,status,duration,created_at from story_audio where story_id=$1 order by created_at desc',[req.params.id]);res.json(rows)});
app.post('/api/stories',auth,async(req,res)=>{const {title,content,ageRange='3–6岁',style='温馨睡前',tags=[]}=req.body||{};if(!title||!content)return res.status(400).json({error:'标题和正文不能为空'});const {rows}=await pool.query('insert into stories(user_id,title,content,age_range,style,tags) values($1,$2,$3,$4,$5,$6) returning *',[req.user.sub,title,content,ageRange,style,tags]);res.status(201).json(rows[0])});
app.post('/api/stories/import',auth,documentUpload.single('document'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'请选择 TXT 或 Word 文档'});try{const content=await extractStoryDocument(req.file);if(content.length>100000)return res.status(400).json({error:'文档正文不能超过 10 万字'});const title=path.basename(req.file.originalname,path.extname(req.file.originalname)).slice(0,200)||'导入的故事';res.json({title,content,source:'import',fileType:path.extname(req.file.originalname).toLowerCase()})}catch(e){res.status(422).json({error:e.message||'文档解析失败'})}finally{fs.unlink(req.file.path,()=>{})}});
app.post('/api/ai/story',auth,async(req,res)=>{const {topic,ageRange='3–6岁',style='温馨睡前',length='约3分钟',character=''}=req.body||{};if(!topic||topic.length>500)return res.status(400).json({error:'请输入不超过 500 字的故事主题'});const task=(await pool.query('insert into ai_tasks(user_id,task_type,status,input_json,started_at) values($1,$2,$3,$4,now()) returning id',[req.user.sub,'story','running',{topic,ageRange,style,length,character}])).rows[0];let result;try{let usage={prompt_tokens:0,completion_tokens:0};let model=null;if(process.env.TEXT_API_URL&&process.env.TEXT_API_KEY){model=await activeModel('text',process.env.TEXT_MODEL);if(isProduction&&!model)throw Error('未配置启用的文字模型定价');const r=await fetch(process.env.TEXT_API_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.TEXT_API_KEY}`},body:JSON.stringify({model:process.env.TEXT_MODEL||'gpt-4o-mini',temperature:.8,response_format:{type:'json_object'},messages:[{role:'system',content:'你是儿童故事作家。只创作安全、温暖、适合儿童的中文故事，不出现暴力、恐怖、危险模仿行为或成人内容。输出 JSON，字段为 title、content、tags。'},{role:'user',content:`年龄：${ageRange}；风格：${style}；长度：${length}；角色：${character||'自定义'}；主题：${topic}`} ]})});if(!r.ok)throw Error(`provider ${r.status}`);const d=await r.json();result={...JSON.parse(d.choices?.[0]?.message?.content||'{}'),source:'provider'};usage=d.usage||usage}else{const title=topic.length>18?topic.slice(0,18)+'…':topic;result={title,content:`在一个${style}的夜晚，${topic}。月光像一条银色的小路，悄悄铺到了窗边。小主人公带着勇气和好奇心，踏上了这段奇妙的旅程。\n\n一路上，它遇见了温柔的朋友，也发现每一次小小的尝试，都会带来闪闪发光的成长。`,tags:[style,'亲子陪伴'],source:'fallback'}}const billing=await chargeUsage({userId:req.user.sub,model,taskId:task.id,category:'text',inputTokens:usage.prompt_tokens,outputTokens:usage.completion_tokens});await pool.query('update ai_tasks set status=$1,output_json=$2,finished_at=now() where id=$3',['succeeded',{...result,billing},task.id]);await audit(req,'ai.story','ai_tasks',task.id,{billing});res.json({...result,taskId:task.id,billing})}catch(e){await pool.query('update ai_tasks set status=$1,error_message=$2,finished_at=now() where id=$3',['failed',e.message,task.id]);res.status(e.code==='INSUFFICIENT_POINTS'?402:502).json({error:e.message==='积分不足，请充值后重试'?e.message:'故事生成失败',taskId:task.id})}});
app.post('/api/ai/tts',auth,async(req,res)=>{const {storyId,text,voice='温柔妈妈',format='mp3'}=req.body||{};if(!storyId||!text||text.length>30000)return res.status(400).json({error:'缺少故事或文本过长'});if(!process.env.TTS_API_URL)return res.status(503).json({error:'TTS 服务尚未配置，请设置 TTS_API_URL'});const own=await pool.query('select id from stories where id=$1 and user_id=$2',[storyId,req.user.sub]);if(!own.rows[0])return res.status(404).json({error:'作品不存在'});let file;try{const model=await activeModel('tts',process.env.TTS_MODEL);if(isProduction&&!model)throw Error('未配置启用的语音模型定价');const r=await fetch(process.env.TTS_API_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.TTS_API_KEY?{Authorization:`Bearer ${process.env.TTS_API_KEY}`}:{})},body:JSON.stringify({text,voice:process.env.TTS_VOICE||voice,format})});if(!r.ok)throw Error(`tts provider ${r.status}`);const name=`${storyId}-${Date.now()}.${format}`;file=path.join(uploadDir,name);fs.writeFileSync(file,Buffer.from(await r.arrayBuffer()));const billing=await chargeUsage({userId:req.user.sub,model,storyId,category:'tts',inputTokens:Math.ceil(text.length/4),outputTokens:0});const {rows}=await pool.query('insert into story_audio(story_id,audio_url,format,status) values($1,$2,$3,$4) returning *',[storyId,`/uploads/${name}`,format,'ready']);res.status(201).json({...rows[0],billing})}catch(e){if(file)fs.unlink(file,()=>{});console.error(e);res.status(e.code==='INSUFFICIENT_POINTS'?402:502).json({error:e.code==='INSUFFICIENT_POINTS'?e.message:'TTS 服务调用失败'})}});
app.post('/api/stories/:id/cover',auth,async(req,res)=>{const story=(await pool.query('select id,title,content from stories where id=$1 and user_id=$2',[req.params.id,req.user.sub])).rows[0];if(!story)return res.status(404).json({error:'作品不存在'});if(!process.env.IMAGE_API_URL)return res.status(503).json({error:'封面绘图服务尚未配置，请设置 IMAGE_API_URL'});try{const model=await activeModel('image',process.env.IMAGE_MODEL);if(isProduction&&!model)throw Error('未配置启用的绘图模型定价');const r=await fetch(process.env.IMAGE_API_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.IMAGE_API_KEY?{Authorization:`Bearer ${process.env.IMAGE_API_KEY}`}:{})},body:JSON.stringify({model:process.env.IMAGE_MODEL,prompt:`儿童绘本风格、温暖低饱和度、无文字封面。故事标题：${story.title}。故事内容：${story.content.slice(0,1200)}`,size:'1024x1024'})});if(!r.ok)throw Error(`image provider ${r.status}`);const out=await r.json();let bytes;if(out?.data?.[0]?.b64_json)bytes=Buffer.from(out.data[0].b64_json,'base64');else if(out?.data?.[0]?.url){const image=await fetch(out.data[0].url);if(!image.ok)throw Error('封面图片下载失败');bytes=Buffer.from(await image.arrayBuffer())}else throw Error('绘图服务未返回图片');const name=`cover-${story.id}-${Date.now()}.png`;fs.writeFileSync(path.join(uploadDir,name),bytes);const usage=out.usage||{};const billing=await chargeUsage({userId:req.user.sub,model,storyId:story.id,category:'image',inputTokens:usage.prompt_tokens||Math.ceil(story.content.length/4),outputTokens:usage.completion_tokens||0});const updated=(await pool.query('update stories set cover_url=$1,updated_at=now() where id=$2 returning id,cover_url,updated_at',[`/uploads/${name}`,story.id])).rows[0];res.json({...updated,billing})}catch(e){console.error(e);res.status(e.code==='INSUFFICIENT_POINTS'?402:502).json({error:e.code==='INSUFFICIENT_POINTS'?e.message:'封面生成失败'})}});
app.patch('/api/stories/:id',auth,async(req,res)=>{const {title,content,status,isPublic}=req.body;const {rows}=await pool.query('update stories set title=coalesce($1,title),content=coalesce($2,content),status=coalesce($3,status),is_public=coalesce($4,is_public),updated_at=now() where id=$5 and user_id=$6 returning *',[title,content,status,isPublic,req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'作品不存在'});res.json(rows[0])});
app.post('/api/checkins',auth,async(req,res)=>{try{const out=await tx(async c=>{const config=(await c.query("select value_json from platform_settings where key='points'")).rows[0]?.value_json||{};const old=await c.query('select consecutive_days from checkin_records where user_id=$1 order by checkin_date desc limit 1',[req.user.sub]);const days=(old.rows[0]?.consecutive_days||0)+1;const earned=days%7===0?Math.max(0,Number(config.seventh_day_bonus||10)):Math.max(0,Number(config.daily_checkin||3));const r=await c.query('insert into checkin_records(user_id,checkin_date,consecutive_days,points_earned) values($1,current_date,$2,$3) returning *',[req.user.sub,days,earned]);const u=await c.query('update users set points=points+$1 where id=$2 returning points',[earned,req.user.sub]);await c.query('insert into points_log(user_id,change_type,amount,balance_after,remark) values($1,$2,$3,$4,$5)',[req.user.sub,'daily_checkin',earned,u.rows[0].points,'每日签到']);return {record:r.rows[0],balance:u.rows[0].points}});res.json(out)}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'今天已经签到':'签到失败'})}});
app.get('/api/admin/dashboard',auth,admin,async(req,res)=>{const [u,s,t,p]=await Promise.all([pool.query('select count(*)::int as count from users'),pool.query('select count(*)::int as count from stories'),pool.query("select count(*)::int as count from ai_tasks where created_at >= current_date"),pool.query("select coalesce(sum(abs(amount)),0)::numeric as total from points_log where amount<0")]);await audit(req,'admin.dashboard','dashboard',null);res.json({users:u.rows[0].count,stories:s.rows[0].count,tasksToday:t.rows[0].count,pointsConsumed:p.rows[0].total})});
app.get('/api/admin/models',auth,admin,async(_,res)=>{const {rows}=await pool.query('select * from ai_models order by created_at desc');res.json(rows)});
app.post('/api/admin/models',auth,admin,async(req,res)=>{const {name,category,provider='custom',modelIdentifier,protocol='openai-compatible',apiUrl='',apiKeyRef='',timeoutMs=30000,maxRetries=2,requestConfig={},pricing={},isEnabled=true}=req.body||{};if(!name||!['text','tts','image'].includes(category)||!apiUrl)return res.status(400).json({error:'请填写模型名称、类型和 Base URL'});if(!Number.isInteger(Number(timeoutMs))||Number(timeoutMs)<1000||Number(timeoutMs)>120000)return res.status(400).json({error:'超时时间应为 1000–120000 毫秒'});const legacyPrice=category==='text'?Number(pricing.inputPerMillion||0):0;const {rows}=await pool.query('insert into ai_models(name,category,provider,model_identifier,protocol,api_url,api_key_ref,timeout_ms,max_retries,request_config,pricing_json,price_per_million,is_enabled) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) returning *',[name,category,provider,modelIdentifier||name,protocol,apiUrl,apiKeyRef,timeoutMs,maxRetries,requestConfig,pricing,legacyPrice,isEnabled]);await audit(req,'admin.model.create','ai_models',rows[0].id,{provider,protocol,category});res.status(201).json(rows[0])});
app.patch('/api/admin/models/:id',auth,admin,async(req,res)=>{const {name,provider,modelIdentifier,protocol,apiUrl,apiKeyRef,timeoutMs,maxRetries,requestConfig,pricing,isEnabled}=req.body||{};const {rows}=await pool.query('update ai_models set name=coalesce($1,name),provider=coalesce($2,provider),model_identifier=coalesce($3,model_identifier),protocol=coalesce($4,protocol),api_url=coalesce($5,api_url),api_key_ref=coalesce($6,api_key_ref),timeout_ms=coalesce($7,timeout_ms),max_retries=coalesce($8,max_retries),request_config=coalesce($9,request_config),pricing_json=coalesce($10,pricing_json),is_enabled=coalesce($11,is_enabled) where id=$12 returning *',[name,provider,modelIdentifier,protocol,apiUrl,apiKeyRef,timeoutMs,maxRetries,requestConfig,pricing,isEnabled,req.params.id]);if(!rows[0])return res.status(404).json({error:'模型不存在'});await audit(req,'admin.model.update','ai_models',rows[0].id,{isEnabled:rows[0].is_enabled});res.json(rows[0])});
app.post('/api/admin/models/:id/test',auth,admin,async(req,res)=>{const model=(await pool.query('select * from ai_models where id=$1',[req.params.id])).rows[0];if(!model)return res.status(404).json({error:'模型不存在'});let url;try{url=new URL(model.api_url)}catch{return res.status(400).json({error:'Base URL 格式不正确'})}if(!['https:','http:'].includes(url.protocol)||['localhost','127.0.0.1','::1'].includes(url.hostname))return res.status(400).json({error:'测试地址不允许指向本机'});const key=/^[A-Z][A-Z0-9_]{1,118}$/.test(model.api_key_ref||'')?process.env[model.api_key_ref]:null;const controller=new AbortController(),started=Date.now(),timeout=setTimeout(()=>controller.abort(),Math.min(Number(model.timeout_ms)||30000,120000));try{const body=model.category==='text'?{model:model.model_identifier,messages:[{role:'user',content:'ping'}],max_tokens:1}:model.category==='tts'?{model:model.model_identifier,text:'测试',format:'mp3'}:{model:model.model_identifier,prompt:'儿童绘本风格的一颗星星',size:'512x512'};const response=await fetch(model.api_url,{method:'POST',headers:{'Content-Type':'application/json',...(key?{Authorization:`Bearer ${key}`}:{})},body:JSON.stringify(body),signal:controller.signal});const elapsedMs=Date.now()-started;const detail=(await response.text()).slice(0,300).replace(/Bearer\s+\S+/gi,'Bearer ***');await audit(req,'admin.model.test','ai_models',model.id,{status:response.status,elapsedMs});res.status(response.ok?200:502).json({ok:response.ok,status:response.status,elapsedMs,detail:response.ok?'连接和鉴权测试成功':detail})}catch(e){res.status(502).json({ok:false,elapsedMs:Date.now()-started,detail:e.name==='AbortError'?'连接超时':String(e.message).slice(0,300)})}finally{clearTimeout(timeout)}});
app.get('/api/admin/users',auth,admin,async(req,res)=>{const query=String(req.query.query||'').trim();const {rows}=await pool.query('select id,phone,nickname,points,role,is_banned,created_at,last_login_at from users where ($1=\'\' or phone ilike $2 or nickname ilike $2) order by created_at desc limit 100',[query,`%${query}%`]);res.json(rows)});
app.post('/api/admin/users/:id/points',auth,admin,async(req,res)=>{const amount=Number(req.body?.amount);const remark=String(req.body?.remark||'管理员调整').trim().slice(0,200);if(!Number.isFinite(amount)||amount===0||Math.abs(amount)>100000)return res.status(400).json({error:'调整积分必须在 -100000 到 100000 之间且不能为 0'});try{const result=await tx(async c=>{const user=(await c.query('select id,points from users where id=$1 for update',[req.params.id])).rows[0];if(!user){const e=Error('用户不存在');e.code='NOT_FOUND';throw e}const balance=Number(user.points)+amount;if(balance<0){const e=Error('扣减后积分不能小于 0');e.code='NEGATIVE';throw e}const updated=(await c.query('update users set points=$1 where id=$2 returning id,phone,nickname,points',[balance,user.id])).rows[0];await c.query('insert into points_log(user_id,change_type,amount,balance_after,remark) values($1,$2,$3,$4,$5)',[user.id,'admin_adjustment',amount,balance,remark]);return updated});await audit(req,'admin.points.adjust','users',result.id,{amount,remark});res.json(result)}catch(e){res.status(e.code==='NOT_FOUND'?404:400).json({error:e.message||'积分调整失败'})}});
app.patch('/api/admin/users/:id',auth,admin,async(req,res)=>{const isBanned=req.body?.isBanned;if(typeof isBanned!=='boolean')return res.status(400).json({error:'仅支持修改用户启用状态'});if(req.params.id===req.user.sub)return res.status(400).json({error:'不能修改当前管理员账号状态'});const {rows}=await pool.query('update users set is_banned=$1 where id=$2 returning id,phone,nickname,points,role,is_banned',[isBanned,req.params.id]);if(!rows[0])return res.status(404).json({error:'用户不存在'});await audit(req,'admin.user.status','users',rows[0].id,{isBanned});res.json(rows[0])});
app.get('/api/admin/ledger',auth,admin,async(_,res)=>{const {rows}=await pool.query('select l.id,l.change_type,l.amount,l.balance_after,l.tokens_consumed,l.remark,l.created_at,u.phone,u.nickname from points_log l join users u on u.id=l.user_id order by l.created_at desc limit 200');res.json(rows)});
app.get('/api/admin/settings',auth,admin,async(_,res)=>{const {rows}=await pool.query("select key,value_json from platform_settings where key in ('points','content_safety') order by key");res.json(Object.fromEntries(rows.map(r=>[r.key,r.value_json])))});
app.put('/api/admin/settings/:key',auth,admin,async(req,res)=>{const key=req.params.key;if(!['points','content_safety'].includes(key)||!req.body?.value||typeof req.body.value!=='object'||Array.isArray(req.body.value))return res.status(400).json({error:'无效的运营配置'});const {rows}=await pool.query('insert into platform_settings(key,value_json,updated_at) values($1,$2,now()) on conflict(key) do update set value_json=excluded.value_json,updated_at=now() returning key,value_json',[key,req.body.value]);await audit(req,'admin.settings.update','platform_settings',rows[0].key,{key});res.json(rows[0])});
app.use('/uploads',express.static(uploadDir)); app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'服务暂时不可用'})});
const server = app.listen(port, process.env.HOST || '127.0.0.1',()=>console.log(`yoyostory api listening on ${port}`));
async function shutdown(signal){console.log(`${signal}: shutting down`);server.close(async()=>{await pool.end();process.exit(0)});setTimeout(()=>process.exit(1),10000).unref()}
process.once('SIGTERM',()=>shutdown('SIGTERM')); process.once('SIGINT',()=>shutdown('SIGINT'));
