import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';
const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT || 4101);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 10, idleTimeoutMillis: 30000 });
const uploadDir = process.env.UPLOAD_DIR || path.join(process.cwd(), 'uploads'); fs.mkdirSync(uploadDir, { recursive: true });
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } })); app.use(cors({ origin: process.env.WEB_ORIGIN || '*', credentials: true })); app.use(express.json({ limit: '1mb' }));
app.use('/api/', rateLimit({ windowMs: 60 * 1000, limit: 100, standardHeaders: true, legacyHeaders: false }));
const upload = multer({ dest: uploadDir, limits: { fileSize: 50 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, /^(audio|video)\//.test(file.mimetype)) });
const sign = user => jwt.sign({ sub: user.id, phone: user.phone }, process.env.JWT_SECRET, { expiresIn: '15m' });
function auth(req,res,next){try{const token=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(token,process.env.JWT_SECRET);next()}catch{res.status(401).json({error:'登录已过期，请重新登录'})}}
async function admin(req,res,next){const {rows}=await pool.query('select role from users where id=$1',[req.user.sub]);if(rows[0]?.role!=='admin')return res.status(403).json({error:'需要管理员权限'});next()}
async function audit(req,action,type,id,metadata={}){await pool.query('insert into audit_logs(user_id,action,resource_type,resource_id,ip_address,metadata) values($1,$2,$3,$4,$5,$6)',[req.user?.sub,action,type,id,req.ip,metadata])}
async function tx(fn){const c=await pool.connect();try{await c.query('begin');const out=await fn(c);await c.query('commit');return out}catch(e){await c.query('rollback');throw e}finally{c.release()}}
app.get('/api/health', async (_,res)=>{try{await pool.query('select 1');res.json({ok:true,service:'yoyostory-api',release:process.env.RELEASE_SHA||'local'})}catch{res.status(503).json({ok:false})}});
app.post('/api/auth/register', async (req,res)=>{const {phone,password,nickname='故事星球用户'}=req.body||{};if(!/^1\d{10}$/.test(phone||'')||!password||password.length<8)return res.status(400).json({error:'手机号或密码格式不正确'});try{const hash=await bcrypt.hash(password,12);const {rows}=await pool.query('insert into users(phone,password_hash,nickname) values($1,$2,$3) returning id,phone,nickname,points',[phone,hash,nickname]);res.status(201).json({token:sign(rows[0]),user:rows[0]})}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'手机号已注册':'注册失败'})}});
app.post('/api/auth/login', async (req,res)=>{const {phone,password}=req.body||{};const {rows}=await pool.query('select id,phone,nickname,points,password_hash,is_banned from users where phone=$1',[phone]);const u=rows[0];if(!u||u.is_banned||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'手机号或密码错误'});delete u.password_hash;res.json({token:sign(u),user:u})});
app.get('/api/me',auth,async(req,res)=>{const {rows}=await pool.query('select id,phone,nickname,points,role,created_at from users where id=$1',[req.user.sub]);res.json(rows[0]||null)});
app.get('/api/billing',auth,async(req,res)=>{const {rows}=await pool.query('select id,change_type,amount,balance_after,tokens_consumed,remark,created_at from points_log where user_id=$1 order by created_at desc limit 100',[req.user.sub]);res.json(rows)});
app.get('/api/tasks/:id',auth,async(req,res)=>{const {rows}=await pool.query('select id,task_type,status,output_json,error_message,created_at,started_at,finished_at from ai_tasks where id=$1 and user_id=$2',[req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'任务不存在'});res.json(rows[0])});
app.get('/api/voices/system',async(_,res)=>{const {rows}=await pool.query('select id,name,description,category,demo_url from system_voices where is_active=true order by sort_order');res.json(rows)});
app.get('/api/voices',auth,async(req,res)=>{const {rows}=await pool.query('select id,name,file_url,duration,quality_score,is_default,status,created_at from voice_samples where user_id=$1 order by created_at desc',[req.user.sub]);res.json(rows)});
app.post('/api/voices/upload',auth,upload.single('audio'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'请上传音频文件'});const count=await pool.query('select count(*) from voice_samples where user_id=$1',[req.user.sub]);if(Number(count.rows[0].count)>=5){fs.unlinkSync(req.file.path);return res.status(409).json({error:'最多保存5组声音样本'})}const {rows}=await pool.query('insert into voice_samples(user_id,name,file_url,quality_score) values($1,$2,$3,$4) returning *',[req.user.sub,req.body.name||'我的声音样本',`/uploads/${req.file.filename}`,92]);res.status(201).json(rows[0])});
app.get('/api/stories',auth,async(req,res)=>{const {rows}=await pool.query('select id,title,content,age_range,style,tags,status,is_public,view_count,like_count,created_at,updated_at from stories where user_id=$1 order by updated_at desc',[req.user.sub]);res.json(rows)});
app.post('/api/stories',auth,async(req,res)=>{const {title,content,ageRange='3–6岁',style='温馨睡前',tags=[]}=req.body||{};if(!title||!content)return res.status(400).json({error:'标题和正文不能为空'});const {rows}=await pool.query('insert into stories(user_id,title,content,age_range,style,tags) values($1,$2,$3,$4,$5,$6) returning *',[req.user.sub,title,content,ageRange,style,tags]);res.status(201).json(rows[0])});
app.post('/api/ai/story',auth,async(req,res)=>{const {topic,ageRange='3–6岁',style='温馨睡前',length='约3分钟',character=''}=req.body||{};if(!topic)return res.status(400).json({error:'请输入故事主题'});const task=(await pool.query('insert into ai_tasks(user_id,task_type,status,input_json) values($1,$2,$3,$4) returning id',[req.user.sub,'story','running',{topic,ageRange,style,length,character}])).rows[0];let result;try{if(process.env.TEXT_API_URL&&process.env.TEXT_API_KEY){const r=await fetch(process.env.TEXT_API_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.TEXT_API_KEY}`},body:JSON.stringify({model:process.env.TEXT_MODEL||'gpt-4o-mini',temperature:.8,response_format:{type:'json_object'},messages:[{role:'system',content:'你是儿童故事作家。只创作安全、温暖、适合儿童的中文故事，不出现暴力、恐怖、危险模仿行为或成人内容。输出 JSON，字段为 title、content、tags。'},{role:'user',content:`年龄：${ageRange}；风格：${style}；长度：${length}；角色：${character||'自定义'}；主题：${topic}`} ]})});if(!r.ok)throw Error(`provider ${r.status}`);const d=await r.json();result={...JSON.parse(d.choices?.[0]?.message?.content||'{}'),source:'provider'}}else{const title=topic.length>18?topic.slice(0,18)+'…':topic;result={title,content:`在一个${style}的夜晚，${topic}。月光像一条银色的小路，悄悄铺到了窗边。小主人公带着勇气和好奇心，踏上了这段奇妙的旅程。\n\n一路上，它遇见了温柔的朋友，也发现每一次小小的尝试，都会带来闪闪发光的成长。`,tags:[style,'亲子陪伴'],source:'fallback'}}await pool.query('update ai_tasks set status=$1,output_json=$2,finished_at=now() where id=$3',['succeeded',result,task.id]);await audit(req,'ai.story','ai_tasks',task.id);res.json({...result,taskId:task.id})}catch(e){await pool.query('update ai_tasks set status=$1,error_message=$2,finished_at=now() where id=$3',['failed',e.message,task.id]);res.status(502).json({error:'故事生成失败',taskId:task.id})}});
app.post('/api/ai/tts',auth,async(req,res)=>{const {storyId,text,voice='温柔妈妈',format='mp3'}=req.body||{};if(!storyId||!text)return res.status(400).json({error:'缺少故事或文本'});if(!process.env.TTS_API_URL)return res.status(503).json({error:'TTS 服务尚未配置，请设置 TTS_API_URL'});try{const r=await fetch(process.env.TTS_API_URL,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.TTS_API_KEY?{Authorization:`Bearer ${process.env.TTS_API_KEY}`}:{})},body:JSON.stringify({text,voice:process.env.TTS_VOICE||voice,format})});if(!r.ok)throw new Error(`tts provider ${r.status}`);const name=`${storyId}-${Date.now()}.${format}`;fs.writeFileSync(path.join(uploadDir,name),Buffer.from(await r.arrayBuffer()));const {rows}=await pool.query('insert into story_audio(story_id,audio_url,format,status) values($1,$2,$3,$4) returning *',[storyId,`/uploads/${name}`,format,'ready']);res.status(201).json(rows[0])}catch(e){console.error(e);res.status(502).json({error:'TTS 服务调用失败'})}});
app.patch('/api/stories/:id',auth,async(req,res)=>{const {title,content,status,isPublic}=req.body;const {rows}=await pool.query('update stories set title=coalesce($1,title),content=coalesce($2,content),status=coalesce($3,status),is_public=coalesce($4,is_public),updated_at=now() where id=$5 and user_id=$6 returning *',[title,content,status,isPublic,req.params.id,req.user.sub]);if(!rows[0])return res.status(404).json({error:'作品不存在'});res.json(rows[0])});
app.post('/api/checkins',auth,async(req,res)=>{try{const out=await tx(async c=>{const old=await c.query('select consecutive_days from checkin_records where user_id=$1 order by checkin_date desc limit 1',[req.user.sub]);const days=(old.rows[0]?.consecutive_days||0)+1;const earned=days%7===0?10:3;const r=await c.query('insert into checkin_records(user_id,checkin_date,consecutive_days,points_earned) values($1,current_date,$2,$3) returning *',[req.user.sub,days,earned]);const u=await c.query('update users set points=points+$1 where id=$2 returning points',[earned,req.user.sub]);await c.query('insert into points_log(user_id,change_type,amount,balance_after,remark) values($1,$2,$3,$4,$5)',[req.user.sub,'daily_checkin',earned,u.rows[0].points,'每日签到']);return {record:r.rows[0],balance:u.rows[0].points}});res.json(out)}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'今天已经签到':'签到失败'})}});
app.get('/api/admin/dashboard',auth,admin,async(req,res)=>{const [u,s,t,p]=await Promise.all([pool.query('select count(*)::int as count from users'),pool.query('select count(*)::int as count from stories'),pool.query("select count(*)::int as count from ai_tasks where created_at >= current_date"),pool.query("select coalesce(sum(abs(amount)),0)::numeric as total from points_log where amount<0")]);await audit(req,'admin.dashboard','dashboard',null);res.json({users:u.rows[0].count,stories:s.rows[0].count,tasksToday:t.rows[0].count,pointsConsumed:p.rows[0].total})});
app.get('/api/admin/models',auth,admin,async(_,res)=>{const {rows}=await pool.query('select * from ai_models order by created_at desc');res.json(rows)});
app.post('/api/admin/models',auth,admin,async(req,res)=>{const {name,category,apiUrl='',pricePerMillion=0,isEnabled=true}=req.body;const {rows}=await pool.query('insert into ai_models(name,category,api_url,price_per_million,is_enabled) values($1,$2,$3,$4,$5) returning *',[name,category,apiUrl,pricePerMillion,isEnabled]);await audit(req,'admin.model.create','ai_models',rows[0].id);res.status(201).json(rows[0])});
app.use('/uploads',express.static(uploadDir)); app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'服务暂时不可用'})});
app.listen(port,'127.0.0.1',()=>console.log(`yoyostory api listening on ${port}`));
